package simpledb.execution;

import simpledb.common.DbException;
import simpledb.storage.RecordId;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;
import simpledb.transaction.TransactionAbortedException;

import java.util.NoSuchElementException;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;

    private OpIterator child1;

    private OpIterator child2;

    private Tuple child1Next;

    private int tupleNo;
    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    /**
     * @return the field name of join field1. Should be quantified by
     *         alias or table name.
     */
    public String getJoinField1Name() {
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return the field name of join field2. Should be quantified by
     *         alias or table name.
     */
    public String getJoinField2Name() {
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *         implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        super.open();
        tupleNo = 0;
    }

    public void close() {
        child1.close();
        child2.close();
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
        tupleNo = 0;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while(child1.hasNext() || child1Next != null) {
            if(child1Next == null) {
                child1Next = child1.next();
            }
            Tuple t1 = child1Next;
            while(child2.hasNext()) {
                Tuple t2 = child2.next();
                if(p.filter(t1, t2)) {
                    Tuple t = new Tuple(getTupleDesc());
                  //  t.setRecordId(new RecordId(t1.getRecordId().getPageId(), tupleNo++));
                    for(int i = 0; i < child1.getTupleDesc().numFields(); i++) {
                        t.setField(i, t1.getField(i));
                    }
                    int index = t1.getTupleDesc().numFields();
                    for(int i = 0; i < child2.getTupleDesc().numFields(); i++) {
                        t.setField(i + index, t2.getField(i));
                    }
                    return t;
                }
            }
            child1Next = null;
            child2.rewind();
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        OpIterator[] childs = new OpIterator[2];
        childs[0] = child1;
        childs[1] = child2;
        return childs;
    }

    @Override
    public void setChildren(OpIterator[] children) {
        child1 = children[0];
        child2 = children[1];
    }

}
